### ISSUE TITLE
PoV Hat Switch Support

### ISSUE THREAD

**Issue by ByALongShot** [RoboPhred/shipbreaker-sixaxis#2]
I'm working on configuring a Thrustmaster T.16000M FCS to use with this mod.  So far the axis mapping is working well for the main joystick movements as follows:

```
devices:
  - # T.16000M FCS
    vendorId: 0x044F
    productId: 0xB10A
axes:
  - axisUsage: 0x30 # GenericDesktop => X
    gameAxis: X
  - axisUsage: 0x31 # GenericDesktop => Y
    gameAxis: Z
    invert: true
  - axisUsage: 0x35 # GenericDesktop => Rz
    gameAxis: Rz
```

The above lets me move horizontally and roll as expected, however I'm now trying to do some mapping for the vertical/Y movement.  I had hoped to use the up/down of the hat switch to control that motion however with the scale being more digital and not mapping cleanly to an analog curve, I don't have a way to map that.

Unsurpsisingly, something like this does not work:
```
  - axisUsage: 0x39 # GenericDesktop => Hat Switch
    gameAxis: Y
    invert: true
```
The default unpressed value forces constant downward movement.  By pressing up, it does move in the correct direction, but that's just by coincidence of the corresponding value, I think.

Ideally, it might be easiest if it were possible to configure each of the 8 directions in the same manner as button events.

Please let me know if there are logs or other details that could assist in making this possible.

![image](https://user-images.githubusercontent.com/3073847/193500499-76099334-94a1-48f4-84f0-5aa06e6d7f0b.png)
